require: rubocop-rspec
AllCops:
  Include:
    - 'lib/gem_footprint_analyzer/**/*.rb'
    - 'exe/*'
    - 'spec/**/*'
  TargetRubyVersion: 2.2

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/gem_footprint_analyzer/require_spy_spec.rb'
    - 'spec/gem_footprint_analyzer/cli_spec.rb'

Style/RegexpLiteral:
  EnforcedStyle: slashes

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/IndentHeredoc:
  Exclude:
    - 'spec/gem_footprint_analyzer/cli_spec.rb'

Style/SignalException:
  EnforcedStyle: semantic

RSpec/NestedGroups:
  Max: 5

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/**/*.rb'

RSpec/MessageSpies:
  EnforcedStyle: receive

Style/DocumentationMethod:
  Enabled: true
