---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
  - 2.2
before_install:
  - gem install bundler -v 1.16.4
script:
  - bundle exec rubocop
  - bundle exec rspec
  - bundle exec analyze_requires -d rubocop
  - bundle exec analyze_requires -g net/http
