---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.3
  - 2.2
before_install:
  - gem install bundler -v 1.17.1
script:
  - bundle exec rubocop
  - bundle exec rspec
  - bundle exec analyze_requires -d rubocop
  - bundle exec analyze_requires net/http
  - bundle exec analyze_requires -g -n1 -d
#  - exe/analyze_requires -n1 net/http|head # Hangs Travis, TODO: investigate
