#!/usr/bin/env ruby --disable=did_you_mean --disable=gem --disable=rubyopt

$LOAD_PATH.unshift(File.join(__dir__, '..', 'lib'))
$LOAD_PATH.unshift('./lib') if Dir.exist?('lib')

require 'gem_footprint_analyzer'

cli = GemFootprintAnalyzer::CLI.new

t1 = Time.now.to_f
cli.run(ARGV)
t2 = Time.now.to_f
puts format("\nTotal runtime %0.4fs", (t2 - t1))
